%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-ifm3d-core
Version:        0.18.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS ifm3d_core package

License:        Apache
URL:            https://github.com/ifm/ifm3d
Source0:        %{name}-%{version}.tar.gz

Requires:       curl
Requires:       glog-devel
Requires:       libcurl-devel
Requires:       pcl-devel
Requires:       ros-noetic-cv-bridge
Requires:       xmlrpc-c-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python3-devel
BuildRequires:  cmake
BuildRequires:  curl
BuildRequires:  glog-devel
BuildRequires:  libcurl-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-noetic-cv-bridge
BuildRequires:  xmlrpc-c-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Library and Utilities for working with ifm pmd-based 3D ToF Cameras

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Jun 02 2020 Sean Kelly <sean.kelly@ifm.com> - 0.18.0-2
- Autogenerated by Bloom

* Tue Jun 02 2020 Sean Kelly <sean.kelly@ifm.com> - 0.18.0-1
- Autogenerated by Bloom

